**TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL NUMPY ARRAYS**

In [1]:
import numpy as

To define a **one-dimensional** array

In [3]:
list_1 = [1, 5, 7, 9, 100, 200, 700, 4]
list_1

[1, 5, 7, 9, 100, 200, 700, 4]

To create a numpy array from the list "my_list"

In [4]:
my_numpy_array = np.array(list_1)
my_numpy_array

array([  1,   5,   7,   9, 100, 200, 700,   4])

To define a **multi-dimensional** array

In [5]:
my_matrix = np.array([[2, 5, 8], [7, 3, 6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

**TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS**

to "rand()" uniform distribution between 0 and 1

In [6]:
x = np.random.rand(20)
x

array([0.549302  , 0.28888892, 0.83258393, 0.49544849, 0.58186851,
       0.45099792, 0.75956992, 0.25476124, 0.96126217, 0.6508218 ,
       0.93907644, 0.76676846, 0.0359709 , 0.13098059, 0.89719756,
       0.82790323, 0.09771499, 0.37959957, 0.70491094, 0.78924455])

to create a matrix of random number

In [7]:
x = np.random.rand(3, 3)
x

array([[0.47657889, 0.75660519, 0.1208113 ],
       [0.83349539, 0.67311317, 0.75100295],
       [0.76750065, 0.58933925, 0.36035965]])

to generate random integers between upper and lower

In [9]:
x = np.random.randint(1, 50)
x

12

to create an evenly spaced values within a given interval

In [10]:
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

to create a diagonal of ones and zeros everywhere else

In [11]:
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

to create the Matrix of ones

In [12]:
x = np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

to create the Array of zeros

In [13]:
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

**TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY**

to return an evenly spaced values within a given interval

In [14]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

to add 2 numpy arrays together

In [15]:
x = np.arange(1, 10)
y = np.arange(2, 11)
sum = x + y
sum

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [16]:
squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [17]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
z = np.exp(y)
z

array([7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
       2.20264658e+04])

**TASK #4: PERFORM ARRAYS SLICING AND INDEXING**

In [19]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

to access specific index from the numpy array

In [20]:
my_numpy_array[0] # the first element of the array

3

My_numpy_array[0:3] selects elements from index 0 to index 3 (exclusive), with a step size of 1. This means that it will return the first three elements of the array.

In [21]:
my_numpy_array[0:3]

array([3, 5, 6])

The first four elements of the my_numpy_array are being assigned the value 7

In [22]:
my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

This function generates random integers from a specified range, in this case, between 1 and 10 (exclusive), and returns an array of the specified shape, in this case, a 4x4 matrix.

In [23]:
matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[4, 5, 6, 6],
       [1, 9, 4, 2],
       [8, 5, 7, 9],
       [3, 1, 1, 9]])

to get a row from a mtrix

In [24]:
matrix[2]

array([8, 5, 7, 9])

**TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)**

This function generates random integers from a specified range, in this case, between 1 and 10 (exclusive), and returns an array of the specified shape, in this case, a 5x5 matrix.

In [25]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[9, 6, 8, 4, 5],
       [9, 6, 5, 5, 1],
       [7, 8, 5, 1, 2],
       [2, 6, 8, 1, 4],
       [5, 3, 2, 5, 1]])

A new array new_matrix is created by selecting elements from the matrix array that are greater than 7.

In [26]:
new_matrix = matrix[matrix>7]
new_matrix

array([9, 8, 9, 8, 8])

A new array new_matrix is created by selecting elements from the matrix array that are odd.

In [27]:
new_matrix = matrix[matrix % 2 == 1]
new_matrix

array([9, 5, 9, 5, 5, 1, 7, 5, 1, 1, 5, 3, 5, 1])

**TASK #6: UNDERSTAND PANDAS FUNDAMENTALS**

In [28]:
import pandas as pd

To define a two-dimensional Pandas DataFrame

In [29]:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [30]:
type(bank_client_df) # obtain the data type

pandas.core.frame.DataFrame

to only view the first couple of rows using .head()

In [31]:
bank_client_df.head(2)

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4

to only view the last row using .tail()

In [32]:
bank_client_df.tail(1)

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
3             444             Ryan           2000                5

**TASK #7: PANDAS WITH CSV AND HTML DATA**

to read tabular data using read_html

In [34]:
house_prices_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

In [35]:
house_prices_df[0]

,City,Average House Price,12 Month Change
0,"Vancouver, BC","$1,036,000",+ 2.63 %
1,"Toronto, Ont","$870,000",+10.2 %
2,"Ottawa, Ont","$479,000",+ 15.4 %
3,"Calgary, Alb","$410,000",– 1.5 %
4,"Montreal, Que","$435,000",+ 9.3 %
5,"Halifax, NS","$331,000",+ 3.6 %
6,"Regina, Sask","$254,000",– 3.9 %
7,"Fredericton, NB","$198,000",– 4.3 %
8,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...

In [36]:
house_prices_df[1]

,Province,Average House Price,12 Month Change
0,British Columbia,"$736,000",+ 7.6 %
1,Ontario,"$594,000",– 3.2 %
2,Alberta,"$353,000",– 7.5 %
3,Quebec,"$340,000",+ 7.6 %
4,Manitoba,"$295,000",– 1.4 %
5,Saskatchewan,"$271,000",– 3.8 %
6,Nova Scotia,"$266,000",+ 3.5 %
7,Prince Edward Island,"$243,000",+ 3.0 %
8,Newfoundland / Labrador,"$236,000",– 1.6 %
9,New Brunswick,"$183,000",– 2.2 %
10,Canadian Average,"$488,000",– 1.3 %
11,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...,(adsbygoogle = window.adsbygoogle || []).push(...

**TASK #8: PANDAS OPERATIONS**

to define a dataframe

In [37]:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

to pick certain rows that satisfy a certain criteria

In [38]:
df_loyal = bank_client_df[ (bank_client_df['Years with bank'] >= 5) ]
df_loyal

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

to delete a column from a DataFrame

In [39]:
del bank_client_df['Bank client ID']
bank_client_df

  Bank Client Name  Net worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

**TASK #9: PANDAS WITH FUNCTIONS**

In [40]:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

to define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake)

In [41]:
def networth_update(balance):
    return balance * 1.2 # assume that stock prices increased by 20%

to apply a function to the DataFrame

In [42]:
bank_client_df['Net worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

This will return a new Series where each element is the length of the corresponding string in the 'Bank Client Name' column

In [43]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

**TASK #10: PERFORM SORTING AND ORDERING IN PANDAS**

In [44]:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444],
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                               'Net worth [$]':[3500, 29000, 10000, 2000],
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

to sort the values in the dataframe according to number of years with bank

In [48]:
bank_client_df.sort_values(by = 'Years with bank', inplace = True)
bank_client_df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

**TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS**

In [51]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
index = [0, 1, 2, 3])
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [52]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
index = [4, 5, 6, 7])
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [53]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
index = [8, 9, 10, 11])
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

The resulting DataFrame will have the same columns as the input DataFrames, and the rows from each input DataFrame will be appended to the end of the previous DataFrame.

In [54]:
pd.concat([df1, df2, df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

**TASK #12: PROJECT AND CONCLUDING REMARKS**

to define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5

In [55]:
raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'],
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1

  Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

to define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)

In [56]:
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'],
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2

  Bank Client ID First Name  Last Name
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

to obtain additional information (Annual Salary) about our bank customers

In [57]:
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary

  Bank Client ID  Annual Salary [$/year]
0              1                   25000
1              2                   35000
2              3                   45000
3              4                   48000
4              5                   49000
5              6                   32000
6              7                   33000
7              8                   34000
8              9                   23000
9             10                   22000

to concatenate both dataframes #1 and #2

In [58]:
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all

  Bank Client ID First Name  Last Name
0              1      Nancy        Rob
1              2       Alex        Ali
2              3       Shep     George
3              4        Max      Mitch
4              5      Allen      Steve
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Bob
4             10      Holly   Michelle

to merge all data on 'Bank Client ID'

In [59]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

  Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000

to add a new client

In [63]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'],
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

  Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

The axis parameter is set to 0, which means that the DataFrames will be concatenated vertically (i.e., stacked on top of each other).

In [64]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

  Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000

**THE END**